-- Complete the migration by dropping old columns, renaming new ones, and adding constraints

-- Step 3: Drop old columns and rename new ones
-- Drop old character varying columns
ALTER TABLE mst_attendance_type DROP COLUMN company_id, DROP COLUMN division_id;
ALTER TABLE mst_cost_category DROP COLUMN company_id, DROP COLUMN division_id;
ALTER TABLE mst_cost_centre DROP COLUMN company_id, DROP COLUMN division_id;
ALTER TABLE mst_employee DROP COLUMN company_id, DROP COLUMN division_id;
ALTER TABLE mst_godown DROP COLUMN company_id, DROP COLUMN division_id;
ALTER TABLE mst_group DROP COLUMN company_id, DROP COLUMN division_id;
ALTER TABLE mst_gst_effective_rate DROP COLUMN company_id, DROP COLUMN division_id;
ALTER TABLE mst_ledger DROP COLUMN company_id, DROP COLUMN division_id;
ALTER TABLE mst_opening_batch_allocation DROP COLUMN company_id, DROP COLUMN division_id;
ALTER TABLE mst_opening_bill_allocation DROP COLUMN company_id, DROP COLUMN division_id;
ALTER TABLE mst_payhead DROP COLUMN company_id, DROP COLUMN division_id;
ALTER TABLE mst_stock_group DROP COLUMN company_id, DROP COLUMN division_id;
ALTER TABLE mst_stock_item DROP COLUMN company_id, DROP COLUMN division_id;
ALTER TABLE mst_stockitem_standard_cost DROP COLUMN company_id, DROP COLUMN division_id;
ALTER TABLE mst_stockitem_standard_price DROP COLUMN company_id, DROP COLUMN division_id;
ALTER TABLE mst_uom DROP COLUMN company_id, DROP COLUMN division_id;
ALTER TABLE mst_vouchertype DROP COLUMN company_id, DROP COLUMN division_id;
ALTER TABLE tally_mst_group DROP COLUMN company_id, DROP COLUMN division_id;
ALTER TABLE tally_mst_ledger DROP COLUMN company_id, DROP COLUMN division_id;
ALTER TABLE tally_mst_stock_item DROP COLUMN company_id, DROP COLUMN division_id;
ALTER TABLE tally_trn_voucher DROP COLUMN company_id, DROP COLUMN division_id;
ALTER TABLE trn_accounting DROP COLUMN company_id, DROP COLUMN division_id;
ALTER TABLE trn_attendance DROP COLUMN company_id, DROP COLUMN division_id;
ALTER TABLE trn_bank DROP COLUMN company_id, DROP COLUMN division_id;
ALTER TABLE trn_batch DROP COLUMN company_id, DROP COLUMN division_id;
ALTER TABLE trn_bill DROP COLUMN company_id, DROP COLUMN division_id;
ALTER TABLE trn_closingstock_ledger DROP COLUMN company_id, DROP COLUMN division_id;
ALTER TABLE trn_cost_category_centre DROP COLUMN company_id, DROP COLUMN division_id;
ALTER TABLE trn_cost_centre DROP COLUMN company_id, DROP COLUMN division_id;
ALTER TABLE trn_cost_inventory_category_centre DROP COLUMN company_id, DROP COLUMN division_id;
ALTER TABLE trn_employee DROP COLUMN company_id, DROP COLUMN division_id;

-- Rename UUID columns to the original names
ALTER TABLE mst_attendance_type RENAME COLUMN company_uuid TO company_id;
ALTER TABLE mst_attendance_type RENAME COLUMN division_uuid TO division_id;
ALTER TABLE mst_cost_category RENAME COLUMN company_uuid TO company_id;
ALTER TABLE mst_cost_category RENAME COLUMN division_uuid TO division_id;
ALTER TABLE mst_cost_centre RENAME COLUMN company_uuid TO company_id;
ALTER TABLE mst_cost_centre RENAME COLUMN division_uuid TO division_id;
ALTER TABLE mst_employee RENAME COLUMN company_uuid TO company_id;
ALTER TABLE mst_employee RENAME COLUMN division_uuid TO division_id;
ALTER TABLE mst_godown RENAME COLUMN company_uuid TO company_id;
ALTER TABLE mst_godown RENAME COLUMN division_uuid TO division_id;
ALTER TABLE mst_group RENAME COLUMN company_uuid TO company_id;
ALTER TABLE mst_group RENAME COLUMN division_uuid TO division_id;
ALTER TABLE mst_gst_effective_rate RENAME COLUMN company_uuid TO company_id;
ALTER TABLE mst_gst_effective_rate RENAME COLUMN division_uuid TO division_id;
ALTER TABLE mst_ledger RENAME COLUMN company_uuid TO company_id;
ALTER TABLE mst_ledger RENAME COLUMN division_uuid TO division_id;
ALTER TABLE mst_opening_batch_allocation RENAME COLUMN company_uuid TO company_id;
ALTER TABLE mst_opening_batch_allocation RENAME COLUMN division_uuid TO division_id;
ALTER TABLE mst_opening_bill_allocation RENAME COLUMN company_uuid TO company_id;
ALTER TABLE mst_opening_bill_allocation RENAME COLUMN division_uuid TO division_id;
ALTER TABLE mst_payhead RENAME COLUMN company_uuid TO company_id;
ALTER TABLE mst_payhead RENAME COLUMN division_uuid TO division_id;
ALTER TABLE mst_stock_group RENAME COLUMN company_uuid TO company_id;
ALTER TABLE mst_stock_group RENAME COLUMN division_uuid TO division_id;
ALTER TABLE mst_stock_item RENAME COLUMN company_uuid TO company_id;
ALTER TABLE mst_stock_item RENAME COLUMN division_uuid TO division_id;
ALTER TABLE mst_stockitem_standard_cost RENAME COLUMN company_uuid TO company_id;
ALTER TABLE mst_stockitem_standard_cost RENAME COLUMN division_uuid TO division_id;
ALTER TABLE mst_stockitem_standard_price RENAME COLUMN company_uuid TO company_id;
ALTER TABLE mst_stockitem_standard_price RENAME COLUMN division_uuid TO division_id;
ALTER TABLE mst_uom RENAME COLUMN company_uuid TO company_id;
ALTER TABLE mst_uom RENAME COLUMN division_uuid TO division_id;
ALTER TABLE mst_vouchertype RENAME COLUMN company_uuid TO company_id;
ALTER TABLE mst_vouchertype RENAME COLUMN division_uuid TO division_id;
ALTER TABLE tally_mst_group RENAME COLUMN company_uuid TO company_id;
ALTER TABLE tally_mst_group RENAME COLUMN division_uuid TO division_id;
ALTER TABLE tally_mst_ledger RENAME COLUMN company_uuid TO company_id;
ALTER TABLE tally_mst_ledger RENAME COLUMN division_uuid TO division_id;
ALTER TABLE tally_mst_stock_item RENAME COLUMN company_uuid TO company_id;
ALTER TABLE tally_mst_stock_item RENAME COLUMN division_uuid TO division_id;
ALTER TABLE tally_trn_voucher RENAME COLUMN company_uuid TO company_id;
ALTER TABLE tally_trn_voucher RENAME COLUMN division_uuid TO division_id;
ALTER TABLE trn_accounting RENAME COLUMN company_uuid TO company_id;
ALTER TABLE trn_accounting RENAME COLUMN division_uuid TO division_id;
ALTER TABLE trn_attendance RENAME COLUMN company_uuid TO company_id;
ALTER TABLE trn_attendance RENAME COLUMN division_uuid TO division_id;
ALTER TABLE trn_bank RENAME COLUMN company_uuid TO company_id;
ALTER TABLE trn_bank RENAME COLUMN division_uuid TO division_id;
ALTER TABLE trn_batch RENAME COLUMN company_uuid TO company_id;
ALTER TABLE trn_batch RENAME COLUMN division_uuid TO division_id;
ALTER TABLE trn_bill RENAME COLUMN company_uuid TO company_id;
ALTER TABLE trn_bill RENAME COLUMN division_uuid TO division_id;
ALTER TABLE trn_closingstock_ledger RENAME COLUMN company_uuid TO company_id;
ALTER TABLE trn_closingstock_ledger RENAME COLUMN division_uuid TO division_id;
ALTER TABLE trn_cost_category_centre RENAME COLUMN company_uuid TO company_id;
ALTER TABLE trn_cost_category_centre RENAME COLUMN division_uuid TO division_id;
ALTER TABLE trn_cost_centre RENAME COLUMN company_uuid TO company_id;
ALTER TABLE trn_cost_centre RENAME COLUMN division_uuid TO division_id;
ALTER TABLE trn_cost_inventory_category_centre RENAME COLUMN company_uuid TO company_id;
ALTER TABLE trn_cost_inventory_category_centre RENAME COLUMN division_uuid TO division_id;
ALTER TABLE trn_employee RENAME COLUMN company_uuid TO company_id;
ALTER TABLE trn_employee RENAME COLUMN division_uuid TO division_id;